/* eslint-disable import/no-cycle */
/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';


/* AUTH */
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS = 'MENU_CHANGE_HAS_SUB_ITEM_STATUS';


/* NOTIFICATION */
export const NOTIFICATION_ALERT_SUCCESS = 'NOTIFICATION_ALERT_SUCCESS';
export const NOTIFICATION_ALERT_ERROR = 'NOTIFICATION_ALERT_ERROR';
export const NOTIFICATION_ALERT_WARNING = 'NOTIFICATION_ALERT_WARNING';

/* TODOAPP */
export const TODO_GET_LIST = 'TODO_GET_LIST';
export const TODO_GET_LIST_SUCCESS = 'TODO_GET_LIST_SUCCESS';
export const TODO_GET_LIST_ERROR = 'TODO_GET_LIST_ERROR';
export const TODO_GET_LIST_WITH_FILTER = 'TODO_GET_LIST_WITH_FILTER';
export const TODO_GET_LIST_WITH_ORDER = 'TODO_GET_LIST_WITH_ORDER';
export const TODO_GET_LIST_SEARCH = 'TODO_GET_LIST_SEARCH';
export const TODO_ADD_ITEM = 'TODO_ADD_ITEM';
export const TODO_ADD_ITEM_SUCCESS = 'TODO_ADD_ITEM_SUCCESS';
export const TODO_ADD_ITEM_ERROR = 'TODO_ADD_ITEM_ERROR';
export const TODO_SELECTED_ITEMS_CHANGE = 'TODO_SELECTED_ITEMS_CHANGE';

/* PRODUCT CATEGORY */
export const PRODUCT_CATEGORY_GET_LIST = 'PRODUCT_CATEGORY_GET_LIST';
export const PRODUCT_CATEGORY_GET_LIST_SUCCESS = 'PRODUCT_CATEGORY_GET_LIST_SUCCESS';
export const PRODUCT_CATEGORY_GET_LIST_ERROR = 'PRODUCT_CATEGORY_GET_LIST_ERROR';
export const PRODUCT_CATEGORY_ADD_ITEM = 'PRODUCT_CATEGORY_ADD_ITEM';
export const PRODUCT_CATEGORY_ADD_ITEM_SUCCESS = 'PRODUCT_CATEGORY_ADD_ITEM_SUCCESS';
export const PRODUCT_CATEGORY_ADD_ITEM_ERROR = 'PRODUCT_CATEGORY_ADD_ITEM_ERROR';
export const PRODUCT_CATEGORY_SELECTED_ITEMS_CHANGE = 'PRODUCT_CATEGORY_SELECTED_ITEMS_CHANGE';
export const PRODUCT_CATEGORY_EDIT = 'PRODUCT_CATEGORY_EDIT';
export const PRODUCT_CATEGORY_CANCEL_EDIT = 'PRODUCT_CATEGORY_CANCEL_EDIT';

/* PRODUCT */
export const PRODUCT_GET_LIST = 'PRODUCT_GET_LIST';
export const PRODUCT_GET_LIST_SUCCESS = 'PRODUCT_GET_LIST_SUCCESS';
export const PRODUCT_GET_LIST_ERROR = 'PRODUCT_GET_LIST_ERROR';
export const PRODUCT_ADD_ITEM = 'PRODUCT_ADD_ITEM';
export const PRODUCT_ADD_ITEM_SUCCESS = 'PRODUCT_ADD_ITEM_SUCCESS';
export const PRODUCT_ADD_ITEM_ERROR = 'PRODUCT_ADD_ITEM_ERROR';
export const PRODUCT_SELECTED_ITEMS_CHANGE = 'PRODUCT_SELECTED_ITEMS_CHANGE';
export const PRODUCT_EDIT = 'PRODUCT_EDIT';
export const PRODUCT_CANCEL_EDIT = 'PRODUCT_CANCEL_EDIT';

/* FAILURE */
export const FAILURE_GET_LIST = 'FAILURE_GET_LIST';
export const FAILURE_GET_LIST_SUCCESS = 'FAILURE_GET_LIST_SUCCESS';
export const FAILURE_GET_LIST_ERROR = 'FAILURE_GET_LIST_ERROR';
export const FAILURE_ADD_ITEM = 'FAILURE_ADD_ITEM';
export const FAILURE_ADD_ITEM_SUCCESS = 'FAILURE_ADD_ITEM_SUCCESS';
export const FAILURE_ADD_ITEM_ERROR = 'FAILURE_ADD_ITEM_ERROR';
export const FAILURE_SELECTED_ITEMS_CHANGE = 'FAILURE_SELECTED_ITEMS_CHANGE';
export const FAILURE_EDIT = 'FAILURE_EDIT';
export const FAILURE_CANCEL_EDIT = 'FAILURE_CANCEL_EDIT';

/* SETTING */
export const SETTING_GET_LIST = 'SETTING_GET_LIST';
export const SETTING_GET_LIST_SUCCESS = 'SETTING_GET_LIST_SUCCESS';
export const SETTING_GET_LIST_ERROR = 'SETTING_GET_LIST_ERROR';
export const SETTING_ADD_ITEM = 'SETTING_ADD_ITEM';
export const SETTING_ADD_ITEM_SUCCESS = 'SETTING_ADD_ITEM_SUCCESS';
export const SETTING_ADD_ITEM_ERROR = 'SETTING_ADD_ITEM_ERROR';
export const SETTING_SELECTED_ITEMS_CHANGE = 'SETTING_SELECTED_ITEMS_CHANGE';
export const SETTING_EDIT = 'SETTING_EDIT';
export const SETTING_CANCEL_EDIT = 'SETTING_CANCEL_EDIT';

/* STATUS */
export const STATUS_GET_LIST = 'STATUS_GET_LIST';
export const STATUS_GET_LIST_SUCCESS = 'STATUS_GET_LIST_SUCCESS';
export const STATUS_GET_LIST_ERROR = 'STATUS_GET_LIST_ERROR';
export const STATUS_ADD_ITEM = 'STATUS_ADD_ITEM';
export const STATUS_ADD_ITEM_SUCCESS = 'STATUS_ADD_ITEM_SUCCESS';
export const STATUS_ADD_ITEM_ERROR = 'STATUS_ADD_ITEM_ERROR';
export const STATUS_SELECTED_ITEMS_CHANGE = 'STATUS_SELECTED_ITEMS_CHANGE';
export const STATUS_EDIT = 'STATUS_EDIT';
export const STATUS_CANCEL_EDIT = 'STATUS_CANCEL_EDIT';

/* Profile */
export const PROFILE_GET_LIST = 'PROFILE_GET_LIST';
export const PROFILE_GET_LIST_SUCCESS = 'PROFILE_GET_LIST_SUCCESS';
export const PROFILE_GET_LIST_ERROR = 'PROFILE_GET_LIST_ERROR';
export const PROFILE_ADD_ITEM = 'PROFILE_ADD_ITEM';
export const PROFILE_ADD_ITEM_SUCCESS = 'PROFILE_ADD_ITEM_SUCCESS';
export const PROFILE_ADD_ITEM_ERROR = 'PROFILE_ADD_ITEM_ERROR';
export const PROFILE_SELECTED_ITEMS_CHANGE = 'PROFILE_SELECTED_ITEMS_CHANGE';
export const PROFILE_EDIT = 'PROFILE_EDIT';
export const PROFILE_CANCEL_EDIT = 'PROFILE_CANCEL_EDIT';

/* Account */
export const ACCOUNT_GET_LIST = 'ACCOUNT_GET_LIST';
export const ACCOUNT_GET_LIST_SUCCESS = 'ACCOUNT_GET_LIST_SUCCESS';
export const ACCOUNT_GET_LIST_ERROR = 'ACCOUNT_GET_LIST_ERROR';
export const ACCOUNT_ADD_ITEM = 'ACCOUNT_ADD_ITEM';
export const ACCOUNT_ADD_ITEM_SUCCESS = 'ACCOUNT_ADD_ITEM_SUCCESS';
export const ACCOUNT_ADD_ITEM_ERROR = 'ACCOUNT_ADD_ITEM_ERROR';
export const ACCOUNT_SELECTED_ITEMS_CHANGE = 'ACCOUNT_SELECTED_ITEMS_CHANGE';
export const ACCOUNT_EDIT = 'ACCOUNT_EDIT';
export const ACCOUNT_CANCEL_EDIT = 'ACCOUNT_CANCEL_EDIT';

/* CHAT APP */
export const CHAT_GET_CONTACTS = 'CHAT_GET_CONTACTS';
export const CHAT_GET_CONTACTS_SUCCESS = 'CHAT_GET_CONTACTS_SUCCESS';
export const CHAT_GET_CONTACTS_ERROR = 'CHAT_GET_CONTACTS_ERROR';
export const CHAT_GET_CONVERSATIONS = 'CHAT_GET_CONVERSATIONS';
export const CHAT_GET_CONVERSATIONS_SUCCESS = 'CHAT_GET_CONVERSATIONS_SUCCESS';
export const CHAT_GET_CONVERSATIONS_ERROR = 'CHAT_GET_CONVERSATIONS_ERROR';
export const CHAT_ADD_MESSAGE_TO_CONVERSATION =
  'CHAT_ADD_MESSAGE_TO_CONVERSATION';
export const CHAT_CREATE_CONVERSATION = 'CHAT_CREATE_CONVERSATION';
export const CHAT_SEARCH_CONTACT = 'CHAT_SEARCH_CONTACT';
export const CHAT_CHANGE_CONVERSATION = 'CHAT_CHANGE_CONVERSATION';

/* SURVEY LIST APP */
export const SURVEY_LIST_GET_LIST = 'SURVEY_LIST_GET_LIST';
export const SURVEY_LIST_GET_LIST_SUCCESS = 'SURVEY_LIST_GET_LIST_SUCCESS';
export const SURVEY_LIST_GET_LIST_ERROR = 'SURVEY_LIST_GET_LIST_ERROR';
export const SURVEY_LIST_GET_LIST_WITH_FILTER =
  'SURVEY_LIST_GET_LIST_WITH_FILTER';
export const SURVEY_LIST_GET_LIST_WITH_ORDER =
  'SURVEY_LIST_GET_LIST_WITH_ORDER';
export const SURVEY_LIST_GET_LIST_SEARCH = 'SURVEY_LIST_GET_LIST_SEARCH';
export const SURVEY_LIST_ADD_ITEM = 'SURVEY_LIST_ADD_ITEM';
export const SURVEY_LIST_ADD_ITEM_SUCCESS = 'SURVEY_LIST_ADD_ITEM_SUCCESS';
export const SURVEY_LIST_ADD_ITEM_ERROR = 'SURVEY_LIST_ADD_ITEM_ERROR';
export const SURVEY_LIST_SELECTED_ITEMS_CHANGE =
  'SURVEY_LIST_SELECTED_ITEMS_CHANGE';

/* SURVEY DETAIL APP */
export const SURVEY_GET_DETAILS = 'SURVEY_GET_DETAILS';
export const SURVEY_GET_DETAILS_SUCCESS = 'SURVEY_GET_DETAILS_SUCCESS';
export const SURVEY_GET_DETAILS_ERROR = 'SURVEY_GET_DETAILS_ERROR';
export const SURVEY_DELETE_QUESTION = 'SURVEY_DELETE_QUESTION';
export const SURVEY_SAVE = 'SURVEY_SAVE';

export * from './status/actions';
export * from './profile/actions';
export * from './product/actions';
export * from './productcategory/actions';
export * from './failure/actions';
export * from './setting/actions';
export * from './dialogModal/actions';
